name: 'vuepress2 builder'
description: 'builder for vuepress'
author: 'yanghq'

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: 'heart'
  color: 'red'

# Define your inputs here.
inputs:
  versionFileName:
    description: 'Save the versionFile'
    required: true
    default: 'package.json'
  versionFileParam:
    description: 'version param Name of the versionFile'
    required: true
    default: 'version'

# Define your outputs here.
outputs:
  time:
    description: 'Your output description here'

runs:
  using: node20
  main: dist/index.js
